# Generated by Django 4.0.5 on 2022-07-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetestapp', '0014_alter_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='timetestapp.tag'),
        ),
    ]
