# Generated by Django 4.0.5 on 2022-07-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetestapp', '0016_alter_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='created',
        ),
    ]
